sudo: required

language: generic
services:
  - docker
script:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker pull onlyofficetestingrobot/doc-builder-testing
  - docker run -e DOCKER_BRANCH=$BRANCH onlyofficetestingrobot/doc-builder-testing